window.PORTFOLIO = {
  email:"zyan2862@gmail.com",
  zh:{
    name:"朱妍", role:"国际体育项目协调者 · 体育管理研究者 · 体育赛事运营者",
    nav:["关于我","专业方向","经历","研究","教育","能力","联系我"],
    heroAccessTitle:["欢迎接入我的","体育世界"],heroExplore:"EXPLORE",messageCard:{hint:"点击留言",title:"给我留言",name:"你的名字",email:"你的邮箱",message:"留言内容",send:"发送留言",close:"关闭",sending:"发送中",success:"留言已发送，谢谢你",activation:"提交成功。若是首次使用，请前往 zyan2862@gmail.com（包括垃圾邮件）点击 FormSubmit 激活邮件",serverRequired:"本地文件模式无法发送，请通过网站服务器打开页面后再试",error:"发送失败，请稍后再试"},
    heroTitle:"连接人、数据与现场，<br>让体育项目真正落地。",
    heroEn:"Connecting People, Data and Operations Through Sport.",
    heroBody:"现居东京，专注于国际体育赛事、体育消费者研究、体育活动运营和跨文化项目协调。",
    tags:["国际体育赛事","体育项目运营","体育管理研究","数据分析","跨文化沟通"],
    buttons:["查看我的经历","查看研究项目","联系我"],
    aboutTitle:"关于我",aboutLead:"我喜欢参与运动，也喜欢走进看台感受比赛；体育既是我的研究对象，也是我选择投入的生活与事业。",
    about:["我来自中国，现居东京，就读于法政大学大学院体育与健康研究科体育管理方向。2027 年起计划进入博士阶段。滑雪、棒球、排球和其他体育现场构成了我的日常兴趣，也让我持续从参与者与观众的角度理解体育。","本科阶段学习土木工程管理，建立了项目管理、统计分析和组织协调基础。北京 2022 冬奥会成为我的职业转折点：我开始理解体育赛事是连接企业、组织、工作人员、观众和城市的复杂项目系统。","目前，我一方面研究体育消费者行为和体育旅游，另一方面持续参与包容性体育和地区体育项目运营。我的优势是把对体育的真实热爱、国际项目经验、研究分析、多语言沟通和现场执行结合起来。"],
    statLabels:["奥运合作伙伴","相关人员数据","雪场调查样本","工作语言"],stats:["13 家","2,000+","约 350","中 · 日 · 英"],
    focusTitle:"核心专业方向",focus:[
      ["01","国际体育赛事","熟悉国际赛事中的合作伙伴沟通、人员信息管理、多语言协调和项目推进。"],
      ["02","体育项目运营","参与前期准备、现场执行、人员引导、竞赛辅助、裁判支持、计时和活动复盘。"],
      ["03","体育研究与数据分析","能够完成问卷设计、实地调查、数据清理、统计分析和研究报告撰写。"],
      ["04","跨文化沟通","使用中文、日语和英语，在不同文化、组织和利益相关者之间推动沟通。"]],
    expTitle:"职业与项目经历", exp:[
      {date:"2026.09 / PLANNED",title:"2026 爱知·名古屋亚运会",role:"国际体育大会运营、翻译与接待",body:"已获得参与资格，计划通过前期培训及现场工作，积累国际综合体育大会的会场运营、人员接待、参与者服务和项目执行经验。",status:"UPCOMING"},
      {date:"2026.06 — NOW",title:"世界ゆるスポーツ協会",role:"体育活动运营实习生",body:"参与活动准备、物资确认、参与者接待、规则说明、裁判与计时辅助、工作坊运营、突发情况处理和复盘。关注参与者是否理解规则、感到安全并愿意再次参加。",status:"INTERNSHIP"},
      {date:"2025 — NOW",title:"地区体育活动与小学生相扑大会",role:"现场运营与体育管理调研",body:"在长野县木曾町等地区活动中负责选手招集、人员与座位引导、流程辅助和动线管理，并提出家长区域、等待路线和低年级选手情绪支持等改善建议。",status:"FIELD"},
      {date:"2021 — 2022",title:"北京 2022 冬季奥运会相关项目",role:"国际合作伙伴协调 · 人员信息与数据管理",body:"对接 13 家奥运合作伙伴企业，管理约 2,000 名相关人员的信息，协助 IOC、合作伙伴与赛事运营组织之间的信息传达、需求整理及项目进度推进。",status:"BEIJING 2022",bullets:["支持 13 家奥运合作伙伴企业","完成约 2,000 人信息整理与管理","在多组织、多语言环境中协调沟通"]}],
    longExperienceUi:{title:"经历",detail:"经历详情",role:"角色",focus:"重点",impact:"影响",duration:"时间"},
    longExperience:[
      {id:"beijing-2022",title:"BEIJING 2022",shortTitle:"北京冬奥会",status:"completed",statusLabel:"已完成",image:"images/beijing-2022-venue.png",alt:"北京2022冬奥会国家跳台滑雪中心夜景",role:"国际合作伙伴服务与项目协调",focusLabel:"工作内容",focus:"负责合作伙伴人员信息整理、需求传达、赛事服务协调及中日英多语言沟通。",impactLabel:"关键职责",impact:"管理13家TOP合作伙伴约2,000名相关人员的数据，并在国际奥委会、合作伙伴与执行团队之间协调复杂需求。",duration:"2021.10 — 2022.03"},
      {id:"yuru-sports",title:"YURU SPORTS",shortTitle:"YURU SPORTS",status:"ongoing",statusLabel:"进行中",image:"images/yuru-sports-arena.png",alt:"YURU SPORTS 赛博体育活动场景",role:"体育活动运营实习生",focusLabel:"工作内容",focus:"参与活动前期准备、现场布置、规则说明、裁判支持、参与者引导及活动结束后的复盘。",impactLabel:"关键职责",impact:"在现场快速理解不同项目规则，协助维持比赛流程，并从参与者动线、规则理解和现场体验角度提出运营改善建议。",duration:"2026.06 — 现在"},
      {id:"asian-games",title:"AICHI-NAGOYA ASIAN GAMES",shortTitle:"爱知名古屋亚运会",status:"upcoming",statusLabel:"即将开始",image:"images/asian-games-service.png",alt:"爱知名古屋亚运会国际接待与语言服务场景",role:"多语言翻译与来宾接待支持",focusLabel:"预计工作内容",focus:"为赛事相关来宾提供中日英翻译、信息说明、现场引导及接待支持。",impactLabel:"核心职责",impact:"准确传达赛事安排和现场信息，协助处理跨语言沟通需求，并配合团队完成来宾接待与现场协调。",duration:"2026.09 — 即将开始"}
    ],
    projectUi:{title:"参与活动",eyebrow:"PROJECT EXPLORER",role:"角色",mission:"项目任务",actions:"具体行动",result:"成果或收获",skills:"能力标签",flip:"点击翻转",back:"返回正面",hover:"悬停展开",drag:"拖动浏览",swipe:"滑动浏览",tap:"点击翻转"},
    projects:[
      {id:"kiso-sumo",number:"01",title:"长野木曾相扑大会",englishTitle:"KISO SUMO TOURNAMENT",category:"FIELD OPS",date:"2026.06",image:"images/sumo-venue-graded.png",alt:"长野木曾小学生相扑大会现场",role:"赛事现场运营支持",mission:"支持小学生相扑大会的招集、人员引导与现场流程运行。",actions:["负责参赛选手招集与候场管理","协助家长区域及观众动线引导","观察比赛流程与现场运营问题","参与赛后复盘并提出改善建议"],result:"提升了传统体育赛事中的现场判断、流程协调与动线改善能力。",skills:["Field Operations","Flow Management","Event Support"]},
      {id:"pickleball",number:"02",title:"匹克球项目策划与现场运营",englishTitle:"PICKLEBALL PROJECT",category:"EVENT OPS",date:"2026",image:"images/pickleball-operations.jpg",alt:"匹克球活动策划与现场运营",role:"项目策划与现场运营支持",mission:"围绕匹克球活动设计项目方案，并支持活动当天的实际运营。",actions:["参与匹克球项目内容与流程设计","准备现场资料、器材及运营物品","协助参与者说明与活动引导","配合处理现场运营问题"],result:"积累了从活动构想到现场执行的项目策划与运营经验。",skills:["Planning","Event Operations","Participant Support"]},
      {id:"campus-activities",number:"03",title:"大学文体部活动策划",englishTitle:"CAMPUS CULTURAL & SPORTS PLANNING",category:"PLANNING",date:"本科期间",image:"images/hosei-baseball-graded.png",alt:"大学体育活动现场",role:"文体活动策划与执行",mission:"策划并组织面向大学生的校园文化与体育活动。",actions:["参与活动主题与形式策划","制定活动流程与执行安排","协调人员、场地和活动资源","支持现场执行与参与者沟通"],result:"建立了从创意形成、资源协调到活动落地的完整策划意识。",skills:["Event Planning","Coordination","Student Leadership"]},
      {id:"super-formula",number:"04",title:"Super Formula 策划",englishTitle:"SUPER FORMULA PLANNING",category:"STRATEGY",date:"时间待确认",image:"images/reel-sport-tech.jpg",alt:"用于呈现 Super Formula 策划的体育科技场景",role:"体育赛事策划与提案",mission:"围绕 Super Formula 的赛事传播、用户体验与活动内容形成策划方案。",actions:["整理赛事与目标用户相关信息","从观众视角分析体验与传播问题","提出活动或内容策划构想","参与方案整理与提案表达"],result:"提升了将赛事价值、用户需求与可执行方案连接起来的策划能力。",skills:["Sports Strategy","Proposal","Audience Insight"]},
      {id:"chiba-tennis",number:"05",title:"千叶网球调查",englishTitle:"CHIBA TENNIS SURVEY",category:"RESEARCH",date:"时间待确认",image:"images/chiba-lotte-survey-graded.png",alt:"千叶体育场馆现场调查",role:"现场调查与观察支持",mission:"在真实赛事环境中观察观众体验、现场氛围与赛事运营。",actions:["参与网球赛事现场观察","记录观众体验与场馆运营情况","整理现场信息与调查内容","从用户视角总结赛事体验特征"],result:"强化了将现场观察转化为用户洞察与研究信息的能力。",skills:["Field Research","Observation","User Insight"]}
    ],
    principle:"在解决问题之前，先理解问题背后的人。",
    researchTitle:"研究：从数据理解体育消费者",researchName:"访日外国人雪上运动旅游<br>中的感知风险与重游意愿研究",
    researchEn:"从数据理解体育消费者",
    researchBody:"研究外国游客在日本参与滑雪或单板滑雪时感受到的安全、语言、天气、装备与信息风险，<br>以及这些因素如何影响其重游意愿，为滑雪场和体育旅游企业提出改善建议。",
    researchStats:[["约 350","有效样本"],["2026.02","长野县现场调查"],["3","问卷语言"],["SEM","结构方程模型"]],
    methods:["计划行为理论","技术接受模型","前景理论","Edgework Theory","问卷设计","数据清理","信效度分析","验证性因子分析","结构方程模型"],
    tools:["SPSS","Mplus","Excel","Google Sheets"],
    eduTitle:"教育经历",education:[["2025 — 2027.03","法政大学大学院","体育与健康研究科 · 体育管理 · 硕士","体育消费者行为、体育旅游、体育营销、国际体育赛事与统计分析"],["2019.09 — 2023.06","北方工业大学","土木工程管理 · Civil Engineering Management","项目管理、工程管理、统计学、成本与进度管理、数据分析及风险管理"]],
    profileFramework:{eyebrow:"06 / PROFILE",title:"SPORT",centerLabel:"MY KEYWORDS",keywords:[{letter:"S",word:"SPIRIT",description:"勇于挑战，在困难面前保持行动力与韧性。"},{letter:"P",word:"PASSION",description:"对体育、项目与成长保持真诚且持续的热情。"},{letter:"O",word:"OPTIMISM",description:"在挑战中保持积极，相信行动能够带来改变。"},{letter:"R",word:"RESEARCH",description:"通过研究与数据发现问题，并形成有依据的洞察。"},{letter:"T",word:"TRANSCULTURAL",description:"跨越语言与文化边界，连接不同的人与组织。"}],languagesTitle:"LANGUAGES",languages:[["中文","母语"],["日语","商务水平"],["英语","商务水平"]],toolsTitle:"TOOLS",tools:[{group:"OFFICE",items:["Word","Excel","PowerPoint"]},{group:"RESEARCH & DATA",items:["SPSS","Mplus"]},{group:"AI WORKFLOW",items:["AI Tools"]}],toolHints:{"Word":"文档与报告","Excel":"数据整理与项目管理","PowerPoint":"演示与提案","SPSS":"统计分析","Mplus":"CFA / SEM","AI Tools":"研究整理与工作流辅助"}},
    skillsTitle:"专业能力",skills:[["赛事与活动运营","国际赛事运营","现场执行","人员引导","竞赛流程","裁判与计时","复盘与改善"],["项目管理","进度跟进","多方协调","需求整理","信息管理","风险识别","现场问题处理"],["研究与数据","问卷设计","定量研究","数据清理","CFA / SEM","文献综述","报告撰写"],["跨文化沟通","中文母语","日语 N1 / 商务沟通","英语 TOEIC 800","国际参与者支持"]],
    contact:{title:"联系我",eyebrow:"联系我",headline:"一起创造<br>更有影响力的体育体验。",message:"期待与你一起创造更有影响力的体育体验。",nameLabel:"姓名",name:"朱妍 / Zhu Yan",schoolLabel:"学校",school:"法政大学大学院 体育健康学研究科",identityLabel:"身份",identity:"硕士课程二年级",phoneLabel:"电话",phone:"090-4282-1181",emailLabel:"邮箱",email:"zyan2862@gmail.com",reveal:"查看",copy:"复制",copied:"已复制",copyFailed:"复制失败，请手动复制",call:"拨打电话",mail:"发送邮件",tokyo:"TOKYO BASED",available:"OPEN TO COLLABORATION",imageAlt:"朱妍的滑雪人物形象",imageFallback:"人物图片待添加"},
    contactTitle:"让我们一起，让体育项目真正落地。",contactBody:"欢迎联系我讨论体育赛事、项目运营、体育研究及中日体育行业合作。",opportunities:["体育行业实习与工作","国际体育项目","体育研究合作","中日体育项目合作"],
    form:["姓名","公司或组织","邮箱","联系主题","留言内容","发送邮件"],footer:"International Sports Project Coordinator · Tokyo"
  },
  ja:{
    name:"朱妍（シュケン）",role:"国際スポーツプロジェクトコーディネーター · スポーツマネジメント研究者 · イベント運営",
    nav:["私について","専門領域","経験","研究","学歴","スキル","連絡"],heroAccessTitle:["私のスポーツの世界へ","アクセス"],heroExplore:"EXPLORE",messageCard:{hint:"メッセージ",title:"メッセージを送る",name:"お名前",email:"メールアドレス",message:"メッセージ",send:"送信",close:"閉じる",sending:"送信中",success:"送信しました ありがとうございます",activation:"送信を受け付けました。初回のみ zyan2862@gmail.com の受信箱（迷惑メールを含む）で FormSubmit を有効化してください",serverRequired:"ローカルファイルでは送信できません。Webサーバー経由で開いてください",error:"送信できませんでした"},heroTitle:"人・データ・現場をつなぎ、<br>スポーツプロジェクトを実現する。",heroEn:"Connecting People, Data and Operations Through Sport.",heroBody:"東京を拠点に、国際スポーツ大会、スポーツ消費者研究、イベント運営、異文化プロジェクト調整に取り組んでいます。",tags:["国際スポーツ大会","プロジェクト運営","スポーツ研究","データ分析","異文化コミュニケーション"],buttons:["経験を見る","研究を見る","お問い合わせ"],
    aboutTitle:"私について",aboutLead:"スポーツを自ら楽しみ、スタンドで試合の熱気を感じることが好きです。スポーツは研究対象であると同時に、私が選んだ生き方とキャリアです。",about:["中国出身、東京在住。法政大学大学院スポーツ健康学研究科でスポーツマネジメントを専攻し、2027年から博士課程進学を予定しています。スキー、野球、バレーボールなどの現場に足を運び、参加者と観客双方の視点からスポーツを捉えています。","学部では土木工程管理を学び、プロジェクト管理、統計分析、組織調整の基礎を身につけました。北京2022を機に、スポーツ業界を長期的なキャリアとして選びました。","現在はスポーツ消費者行動とツーリズムを研究しながら、インクルーシブスポーツや地域スポーツの現場運営に参加しています。スポーツへの情熱と、研究、国際経験、多言語コミュニケーション、現場実行力を結びつけることが私の強みです。"],
    statLabels:["オリンピックパートナー","関係者データ","調査サンプル","使用言語"],stats:["13社","2,000+","約350","中 · 日 · 英"],
    focusTitle:"専門領域",focus:[["01","国際スポーツ大会","パートナー対応、関係者情報管理、多言語調整、プロジェクト推進。"],["02","スポーツ運営","準備、現場実施、誘導、競技補助、審判・計時、振り返り。"],["03","研究・データ分析","質問紙設計、現地調査、データ整備、統計分析、研究報告。"],["04","異文化コミュニケーション","中国語・日本語・英語で組織とステークホルダーをつなぐ。"]],
    expTitle:"実務・プロジェクト経験",exp:[{date:"2026.09 / 予定",title:"愛知・名古屋2026アジア競技大会",role:"大会運営・通訳・接遇",body:"参加資格を取得。研修と大会現場を通じ、会場運営、参加者サービス、国際大会の実行経験を積む予定です。",status:"UPCOMING"},{date:"2026.06 — 現在",title:"世界ゆるスポーツ協会",role:"イベント運営インターン",body:"準備、物品確認、参加者対応、ルール説明、審判・計時補助、ワークショップ、現場対応、振り返りに参加しています。",status:"INTERNSHIP"},{date:"2025 — 現在",title:"地域スポーツ・小学生相撲大会",role:"現場運営・調査",body:"長野県木曽町などで選手招集、誘導、競技進行、動線管理を担当し、観戦区域や低学年選手の感情支援などを提案しました。",status:"FIELD"},{date:"2021 — 2022",title:"北京2022冬季オリンピック関連プロジェクト",role:"国際パートナー調整 · 人員データ管理",body:"13社のオリンピックパートナーと連携し、約2,000名の情報を管理。IOC、企業、運営組織間の情報伝達と進行を支援しました。",status:"BEIJING 2022",bullets:["パートナー13社を支援","約2,000名のデータ管理","多組織・多言語環境での調整"]}],
    longExperienceUi:{title:"経験",detail:"経験詳細",role:"役割",focus:"重点",impact:"影響",duration:"期間"},
    longExperience:[
      {id:"beijing-2022",title:"BEIJING 2022",shortTitle:"北京冬季五輪",status:"completed",statusLabel:"完了",image:"images/beijing-2022-venue.png",alt:"北京2022冬季オリンピック国家スキージャンプセンターの夜景",role:"国際パートナーサービス・調整",focus:"データ · コミュニケーション · ステークホルダー",impactLabel:"影響",impact:"国際大会で複雑なニーズを整理し、調整する経験を得ました。",duration:"2021.07 — 2022.02"},
      {id:"yuru-sports",title:"YURU SPORTS",shortTitle:"ゆるスポーツ",status:"ongoing",statusLabel:"進行中",image:"images/yuru-sports-arena.png",alt:"ゆるスポーツのサイバーイベント会場",role:"イベント運営インターン",focus:"現場支援 · 参加者対応 · 運営改善",impactLabel:"影響",impact:"イベント運営と参加者支援の実践力を高めました。",duration:"2026.04 — 現在"},
      {id:"asian-games",title:"AICHI-NAGOYA ASIAN GAMES",shortTitle:"愛知・名古屋アジア競技大会",status:"upcoming",statusLabel:"予定",image:"images/asian-games-service.png",alt:"愛知・名古屋アジア競技大会の国際受付・言語サポート場面",role:"国際大会サービス支援",focus:"異文化コミュニケーション · 来賓支援 · 大会運営連携",impactLabel:"期待する貢献",impact:"国際大会の現場支援と調整業務に参加する予定です。",duration:"2026.09 — 予定"}
    ],
    projectUi:{title:"参加活動",eyebrow:"PROJECT EXPLORER",role:"役割",mission:"ミッション",actions:"アクション",result:"成果・学び",skills:"スキル",flip:"クリックで反転",back:"表面に戻る",hover:"ホバーで拡大",drag:"ドラッグして見る",swipe:"スワイプして見る",tap:"タップで反転"},
    projects:[
      {id:"kiso-sumo",number:"01",title:"長野木曽相撲大会",englishTitle:"KISO SUMO TOURNAMENT",category:"FIELD OPS",date:"2026.06",image:"images/sumo-venue-graded.png",alt:"長野木曽の小学生相撲大会",role:"大会現場運営サポート",mission:"小学生相撲大会の招集、誘導、現場進行を支援する。",actions:["選手招集と待機エリアを管理","保護者エリアと観客動線を案内","競技進行と運営課題を観察","振り返りに参加し改善案を提案"],result:"伝統スポーツ大会での現場判断、進行調整、動線改善力を高めました。",skills:["Field Operations","Flow Management","Event Support"]},
      {id:"pickleball",number:"02",title:"ピックルボール企画・現場運営",englishTitle:"PICKLEBALL PROJECT",category:"EVENT OPS",date:"2026",image:"images/pickleball-operations.jpg",alt:"ピックルボールイベントの企画と現場運営",role:"企画・現場運営サポート",mission:"ピックルボール企画を設計し、イベント当日の運営を支援する。",actions:["企画内容と進行を設計","資料、用具、運営物品を準備","参加者への説明と誘導を支援","現場の運営課題に対応"],result:"企画構想から現場実施までのイベント運営経験を積みました。",skills:["Planning","Event Operations","Participant Support"]},
      {id:"campus-activities",number:"03",title:"大学文化・スポーツ活動企画",englishTitle:"CAMPUS CULTURAL & SPORTS PLANNING",category:"PLANNING",date:"学部在学中",image:"images/hosei-baseball-graded.png",alt:"大学スポーツ活動の会場",role:"文化・スポーツ活動の企画・実施",mission:"大学生向けの文化・スポーツ活動を企画し運営する。",actions:["テーマと形式を企画","進行と実施計画を作成","人員、会場、資源を調整","現場実施と参加者対応を支援"],result:"アイデア形成から資源調整、実施までの一連の企画意識を身につけました。",skills:["Event Planning","Coordination","Student Leadership"]},
      {id:"super-formula",number:"04",title:"Super Formula 企画",englishTitle:"SUPER FORMULA PLANNING",category:"STRATEGY",date:"時期確認中",image:"images/reel-sport-tech.jpg",alt:"Super Formula企画を表すスポーツテクノロジー場面",role:"スポーツ大会企画・提案",mission:"Super Formulaの発信、観客体験、活動内容に関する企画案を作成する。",actions:["大会と対象ユーザー情報を整理","観客視点で体験と発信課題を分析","活動・コンテンツ案を提案","企画書とプレゼンを作成"],result:"大会価値、ユーザーニーズ、実行可能な案を結ぶ企画力を高めました。",skills:["Sports Strategy","Proposal","Audience Insight"]},
      {id:"chiba-tennis",number:"05",title:"千葉テニス調査",englishTitle:"CHIBA TENNIS SURVEY",category:"RESEARCH",date:"時期確認中",image:"images/chiba-lotte-survey-graded.png",alt:"千葉のスポーツ会場での現地調査",role:"現地調査・観察サポート",mission:"実際の大会環境で観客体験、会場の雰囲気、運営を観察する。",actions:["テニス大会の現場を観察","観客体験と会場運営を記録","現地情報と調査内容を整理","ユーザー視点で体験特性をまとめる"],result:"現場観察をユーザー洞察と研究情報へ変換する力を強化しました。",skills:["Field Research","Observation","User Insight"]}
    ],
    principle:"問題を解決する前に、その背景にいる人を理解する。",researchTitle:"研究：データからスポーツ消費者を理解する",researchName:"訪日外国人のスノースポーツ観光における<br>知覚リスクと再訪意向",researchEn:"データからスポーツ消費者を理解する",researchBody:"安全、言語、天候、用具、情報に関するリスク認知が再訪意向に与える影響を分析し、<br>スキー場とスポーツツーリズム事業者への提言を目指します。",researchStats:[["約350","有効回答"],["2026.02","長野県現地調査"],["3","調査言語"],["SEM","構造方程式モデル"]],methods:["計画的行動理論","技術受容モデル","プロスペクト理論","Edgework Theory","質問紙設計","データクリーニング","信頼性・妥当性","CFA","SEM"],tools:["SPSS","Mplus","Excel","Google Sheets"],
    eduTitle:"学歴",education:[["2025 — 2027.03","法政大学大学院","スポーツ健康学研究科 · スポーツマネジメント · 修士","スポーツ消費者行動、ツーリズム、マーケティング、国際大会、統計分析"],["2019.09 — 2023.06","北方工業大学","土木工程管理","プロジェクト管理、統計学、コスト・工程管理、データ分析、リスク管理"]],
    profileFramework:{eyebrow:"06 / PROFILE",title:"SPORT",centerLabel:"MY KEYWORDS",keywords:[{letter:"S",word:"SPIRIT",description:"困難に直面しても、挑戦する気持ちと行動力を持ち続ける。"},{letter:"P",word:"PASSION",description:"スポーツ、プロジェクト、成長に対して誠実で持続的な情熱を持つ。"},{letter:"O",word:"OPTIMISM",description:"困難の中でも前向きさを保ち、行動が変化を生むと信じる。"},{letter:"R",word:"RESEARCH",description:"研究とデータを通じて課題を見つけ、根拠ある洞察を導く。"},{letter:"T",word:"TRANSCULTURAL",description:"言語や文化の境界を越え、人と組織をつなぐ。"}],languagesTitle:"LANGUAGES",languages:[["中国語","母語"],["日本語","ビジネスレベル"],["英語","ビジネスレベル"]],toolsTitle:"TOOLS",tools:[{group:"OFFICE",items:["Word","Excel","PowerPoint"]},{group:"RESEARCH & DATA",items:["SPSS","Mplus"]},{group:"AI WORKFLOW",items:["AI Tools"]}],toolHints:{"Word":"文書・レポート","Excel":"データ整理・プロジェクト管理","PowerPoint":"プレゼンテーション・提案","SPSS":"統計分析","Mplus":"CFA / SEM","AI Tools":"研究整理・ワークフロー支援"}},
    skillsTitle:"専門スキル",skills:[["大会・イベント運営","国際大会","現場実施","誘導","競技進行","審判・計時","改善提案"],["プロジェクト管理","進捗管理","多者間調整","要件整理","情報管理","リスク特定"],["研究・データ","質問紙設計","定量研究","データ整備","CFA / SEM","報告書"],["異文化対応","中国語母語","日本語N1・ビジネス","英語TOEIC 800","国際参加者支援"]],
    contact:{title:"お問い合わせ",eyebrow:"お問い合わせ",headline:"スポーツを通じて<br>新しい価値を共に。",message:"スポーツを通じて、新しい価値とインパクトを一緒に創りましょう。",nameLabel:"氏名",name:"朱妍 / Zhu Yan",schoolLabel:"所属",school:"法政大学大学院 スポーツ健康学研究科",identityLabel:"身分",identity:"修士課程2年",phoneLabel:"電話",phone:"090-4282-1181",emailLabel:"メール",email:"zyan2862@gmail.com",reveal:"表示",copy:"コピー",copied:"コピーしました",copyFailed:"コピーできませんでした",call:"電話する",mail:"メールを送る",tokyo:"TOKYO BASED",available:"OPEN TO COLLABORATION",imageAlt:"朱妍のスノーボード・キャラクター",imageFallback:"人物画像を追加してください"},
    contactTitle:"スポーツプロジェクトを、一緒に現場へ。",contactBody:"大会運営、スポーツ研究、日中スポーツ協力についてお気軽にご連絡ください。",opportunities:["スポーツ業界の仕事・インターン","国際スポーツプロジェクト","共同研究","日中スポーツ協力"],form:["氏名","会社・組織","メール","件名","メッセージ","メールを送る"],footer:"International Sports Project Coordinator · Tokyo"
  },
  en:{
    name:"Yan Zhu",role:"International Sports Project Coordinator · Sport Management Researcher · Event Operations Professional",
    nav:["About","Focus","Experience","Research","Education","Skills","Contact"],heroAccessTitle:["Welcome to my","world of sport"],heroExplore:"EXPLORE",messageCard:{hint:"LEAVE A MESSAGE",title:"Leave a message",name:"Your name",email:"Your email",message:"Message",send:"Send message",close:"Close",sending:"Sending",success:"Message sent Thank you",activation:"Submitted. For first-time setup, open the FormSubmit activation email sent to zyan2862@gmail.com, including Spam",serverRequired:"Messages cannot be sent from a local file. Open the site through a web server",error:"Unable to send Please try again"},heroTitle:"Connecting People, Data<br>and Operations Through Sport.",heroEn:"INTERNATIONAL SPORT × RESEARCH × FIELD",heroBody:"Based in Tokyo, I focus on international sport events, sport consumer research, field operations, and cross-cultural project coordination.",tags:["International events","Project operations","Sport research","Data analysis","Cross-cultural communication"],buttons:["View experience","View research","Contact me"],
    aboutTitle:"About me",aboutLead:"I love taking part in sport and feeling the energy of a live match. Sport is not only what I research—it is the life and career I have chosen.",about:["Originally from China and based in Tokyo, I am a second-year master’s student in Sport and Health Studies at Hosei University, specializing in sport management. I plan to begin doctoral study in 2027. Skiing, baseball, volleyball, and other live sport settings shape how I understand both participants and spectators.","My undergraduate background in Civil Engineering Management built a foundation in project management, statistics, risk, and organizational coordination. Beijing 2022 became the turning point that led me to pursue sport as a long-term career.","Today I combine a genuine passion for sport with consumer and tourism research, international project experience, multilingual communication, and hands-on operations in inclusive and community sport."],
    statLabels:["Olympic partners","Personnel records","Survey sample","Working languages"],stats:["13","2,000+","≈350","ZH · JA · EN"],
    focusTitle:"Core focus",focus:[["01","International sport events","Partner communication, personnel information, multilingual coordination, and project delivery."],["02","Sport project operations","Preparation, field execution, participant guidance, competition support, officiating, timing, and review."],["03","Research & data analysis","Questionnaire design, fieldwork, data cleaning, statistical analysis, and reporting."],["04","Cross-cultural communication","Connecting needs across cultures, organizations, and stakeholders in Chinese, Japanese, and English."]],
    expTitle:"Experience & projects",exp:[{date:"SEP 2026 / PLANNED",title:"Aichi-Nagoya 2026 Asian Games",role:"International event operations, interpretation & reception",body:"Selected to participate. I plan to build further experience in venue operations, participant service, reception, and international event delivery.",status:"UPCOMING"},{date:"JUN 2026 — NOW",title:"World Yuru Sports Association",role:"Sport Event Operations Intern",body:"Supporting preparation, equipment checks, participant service, rule briefing, officiating and timing, workshops, incident response, and post-event review.",status:"INTERNSHIP"},{date:"2025 — NOW",title:"Community Sport & Youth Sumo Events",role:"Field Operations & Research",body:"Supporting athlete calls, participant flow, competition processes, seating, and movement at events including a youth sumo tournament in Kiso, Nagano; proposing experience improvements.",status:"FIELD"},{date:"2021 — 2022",title:"Beijing 2022 Winter Olympic Games Project",role:"International Partner Coordination · Personnel Data",body:"Coordinated with 13 Olympic partner companies and managed information for approximately 2,000 people, supporting communication and delivery across the IOC, partners, and operations teams.",status:"BEIJING 2022",bullets:["Supported 13 Olympic partners","Managed ≈2,000 personnel records","Delivered in a multilingual, multi-organization environment"]}],
    longExperienceUi:{title:"Experience",detail:"EXPERIENCE DETAIL",role:"ROLE",focus:"FOCUS",impact:"IMPACT",duration:"DURATION"},
    longExperience:[
      {id:"beijing-2022",title:"BEIJING 2022",shortTitle:"Beijing Winter Olympics",status:"completed",statusLabel:"COMPLETED",image:"images/beijing-2022-venue.png",alt:"Beijing 2022 National Ski Jumping Centre at night",role:"International Partner Service & Coordination",focus:"Data · Communication · Stakeholders",impactLabel:"IMPACT",impact:"Learned to manage and coordinate complex needs in a global event.",duration:"2021.07 — 2022.02"},
      {id:"yuru-sports",title:"YURU SPORTS",shortTitle:"Yuru Sports",status:"ongoing",statusLabel:"ONGOING",image:"images/yuru-sports-arena.png",alt:"Cyber-styled Yuru Sports event arena",role:"Sport Event Operations Intern",focus:"On-site Support · Facilitation · Operations Improvement",impactLabel:"IMPACT",impact:"Developed practical event-operation and participant-support skills.",duration:"2026.04 — Present"},
      {id:"asian-games",title:"AICHI-NAGOYA ASIAN GAMES",shortTitle:"AICHI-NAGOYA ASIAN GAMES",status:"upcoming",statusLabel:"UPCOMING",image:"images/asian-games-service.png",alt:"Aichi-Nagoya Asian Games international reception and language-support scene",role:"International Event Service Support",focus:"Cross-cultural Communication · Guest Support · Event Operations",impactLabel:"EXPECTED CONTRIBUTION",impact:"Preparing to support and coordinate international event operations.",duration:"2026.09 — UPCOMING"}
    ],
    projectUi:{title:"Activities",eyebrow:"PROJECT EXPLORER",role:"ROLE",mission:"MISSION",actions:"ACTION",result:"RESULT",skills:"SKILLS",flip:"CLICK TO FLIP",back:"FLIP BACK",hover:"HOVER TO EXPAND",drag:"DRAG TO EXPLORE",swipe:"SWIPE TO EXPLORE",tap:"TAP TO FLIP"},
    projects:[
      {id:"kiso-sumo",number:"01",title:"Kiso Sumo Tournament",englishTitle:"KISO SUMO TOURNAMENT",category:"FIELD OPS",date:"2026.06",image:"images/sumo-venue-graded.png",alt:"Youth sumo tournament in Kiso, Nagano",role:"Event field-operations support",mission:"Support athlete calls, participant guidance, and live competition flow at a youth sumo tournament.",actions:["Managed athlete calls and waiting areas","Guided parent zones and spectator flow","Observed competition and operational issues","Joined the review and proposed improvements"],result:"Strengthened field judgment, flow coordination, and movement-planning skills in a traditional sport event.",skills:["Field Operations","Flow Management","Event Support"]},
      {id:"pickleball",number:"02",title:"Pickleball Project",englishTitle:"PICKLEBALL PROJECT",category:"EVENT OPS",date:"2026",image:"images/pickleball-operations.jpg",alt:"Pickleball project planning and field operations",role:"Project planning and event-operations support",mission:"Design a pickleball activity plan and support its event-day delivery.",actions:["Helped design content and activity flow","Prepared materials, equipment, and supplies","Supported participant briefing and guidance","Helped resolve on-site operational issues"],result:"Built practical experience connecting an event concept with real-world delivery.",skills:["Planning","Event Operations","Participant Support"]},
      {id:"campus-activities",number:"03",title:"Campus Cultural & Sports Planning",englishTitle:"CAMPUS CULTURAL & SPORTS PLANNING",category:"PLANNING",date:"Undergraduate",image:"images/hosei-baseball-graded.png",alt:"University sport activity venue",role:"Cultural and sport activity planning",mission:"Plan and organize cultural and sport activities for university students.",actions:["Developed themes and activity formats","Built schedules and delivery plans","Coordinated people, venues, and resources","Supported on-site delivery and communication"],result:"Developed an end-to-end planning mindset from concept and coordination to execution.",skills:["Event Planning","Coordination","Student Leadership"]},
      {id:"super-formula",number:"04",title:"Super Formula Planning",englishTitle:"SUPER FORMULA PLANNING",category:"STRATEGY",date:"To be confirmed",image:"images/reel-sport-tech.jpg",alt:"Sport technology setting representing Super Formula planning",role:"Sport-event planning and proposal",mission:"Develop a proposal around Super Formula communication, audience experience, and event content.",actions:["Organized event and target-audience information","Analyzed experience and communication issues","Proposed activation and content concepts","Supported proposal development and presentation"],result:"Improved the ability to connect event value and audience needs with executable ideas.",skills:["Sports Strategy","Proposal","Audience Insight"]},
      {id:"chiba-tennis",number:"05",title:"Chiba Tennis Survey",englishTitle:"CHIBA TENNIS SURVEY",category:"RESEARCH",date:"To be confirmed",image:"images/chiba-lotte-survey-graded.png",alt:"Field research at a sport venue in Chiba",role:"Field research and observation support",mission:"Observe audience experience, venue atmosphere, and operations in a live event setting.",actions:["Observed a tennis event on site","Recorded audience experience and venue operations","Organized field notes and research material","Summarized experience patterns from a user perspective"],result:"Strengthened the ability to turn field observation into user insight and research information.",skills:["Field Research","Observation","User Insight"]}
    ],
    principle:"Before solving the problem, understand the person behind it.",researchTitle:"Research: understanding sport consumers through data",researchName:"Perceived Risk and Revisit Intention in<br>Inbound Snow Sports Tourism in Japan",researchEn:"Understanding Sport Consumers Through Data",researchBody:"This study examines how safety, language, weather, equipment, and information risks shape revisit intention<br>among international snow-sport tourists, with practical recommendations for Japanese resorts and businesses.",researchStats:[["≈350","Valid responses"],["FEB 2026","Nagano fieldwork"],["3","Survey languages"],["SEM","Structural model"]],methods:["Theory of Planned Behavior","Technology Acceptance Model","Prospect Theory","Edgework Theory","Questionnaire design","Data cleaning","Reliability & validity","CFA","SEM"],tools:["SPSS","Mplus","Excel","Google Sheets"],
    eduTitle:"Education",education:[["2025 — MAR 2027","Hosei University Graduate School","M.A., Sport and Health Studies · Sport Management","Sport consumer behavior, tourism, marketing, international events, and statistics"],["SEP 2019 — JUN 2023","North China University of Technology","B.A., Civil Engineering Management","Project management, statistics, cost and schedule, data analysis, and risk management"]],
    profileFramework:{eyebrow:"06 / PROFILE",title:"SPORT",centerLabel:"WHAT DEFINES ME",keywords:[{letter:"S",word:"SPIRIT",description:"Staying courageous and resilient in the face of challenges."},{letter:"P",word:"PASSION",description:"Driven by a genuine and lasting passion for sport, projects, and growth."},{letter:"O",word:"OPTIMISM",description:"Remaining positive through challenges and believing in the power of action."},{letter:"R",word:"RESEARCH",description:"Using research and data to identify problems and generate insight."},{letter:"T",word:"TRANSCULTURAL",description:"Connecting people and organizations across languages and cultures."}],languagesTitle:"LANGUAGES",languages:[["Chinese","Native"],["Japanese","Business level"],["English","Business level"]],toolsTitle:"TOOLS",tools:[{group:"OFFICE",items:["Word","Excel","PowerPoint"]},{group:"RESEARCH & DATA",items:["SPSS","Mplus"]},{group:"AI WORKFLOW",items:["AI Tools"]}],toolHints:{"Word":"Documents & Reports","Excel":"Data & Project Management","PowerPoint":"Presentation & Proposal","SPSS":"Statistical Analysis","Mplus":"CFA & SEM","AI Tools":"Research & Workflow"}},
    skillsTitle:"Professional capabilities",skills:[["Event operations","International events","Field execution","Guidance","Competition flow","Officiating & timing","Review"],["Project management","Progress tracking","Stakeholder coordination","Requirements","Information","Risk identification"],["Research & data","Questionnaires","Quantitative research","Data cleaning","CFA / SEM","Reporting"],["Cross-cultural","Native Chinese","Japanese N1 / business","English TOEIC 800","International support"]],
    contact:{title:"CONTACT",eyebrow:"CONTACT ME",headline:"LET'S CREATE<br>IMPACT TOGETHER.",message:"Let’s create meaningful impact through sport together.",nameLabel:"Name",name:"Zhu Yan",schoolLabel:"School",school:"Graduate School of Sports and Health Studies, Hosei University",identityLabel:"Status",identity:"Second-year Master’s Student",phoneLabel:"Tel",phone:"090-4282-1181",emailLabel:"Mail",email:"zyan2862@gmail.com",reveal:"View",copy:"Copy",copied:"Copied",copyFailed:"Unable to copy",call:"Call",mail:"Send email",tokyo:"TOKYO BASED",available:"OPEN TO COLLABORATION",imageAlt:"Snowboard character portrait of Zhu Yan",imageFallback:"Character image coming soon"},
    contactTitle:"Let’s move sport projects from idea to field.",contactBody:"I welcome conversations about sport events, project operations, research, and China–Japan sport collaboration.",opportunities:["Sport industry roles & internships","International sport projects","Research collaboration","China–Japan sport partnerships"],form:["Name","Company or organization","Email","Subject","Message","Open email"],footer:"International Sports Project Coordinator · Tokyo"
  }
};
window.PORTFOLIO.zh.contact.message="欢迎与我联系，期待与您的合作。";
window.PORTFOLIO.ja.contact.message="お気軽にご連絡ください。皆さまとの協働を楽しみにしています。";
window.PORTFOLIO.en.contact.message="Please feel free to contact me. I look forward to working with you.";
window.SKILLS_UI={
  zh:{portfolio:"PORTFOLIO",section:"SKILLS",identity:"WHO I AM",number:"03",title:"MY KEYWORDS",subtitle:"FIVE QUALITIES THAT SHAPE WHO I AM.",action:"IN ACTION",hover:"HOVER OVER A LETTER",cards:[["♜","SPIRIT","brave in challenges","勇于迎接挑战，在压力与困难中保持韧性、正直和持续行动。"],["⌁","PASSION","driven by love for sport","对体育、项目与成长保持真诚且持续的热情。"],["☼","OPTIMISM","positive through complexity","在复杂挑战中保持积极，相信行动能够带来改变。"],["▥","RESEARCH","insight through data","通过研究与数据发现问题，并形成有依据的洞察。"],["◎","TRANSCULTURAL","connecting across cultures","跨越语言与文化边界，连接不同的人与组织。"]]},
  ja:{portfolio:"PORTFOLIO",section:"SKILLS",identity:"WHO I AM",number:"03",title:"MY KEYWORDS",subtitle:"FIVE QUALITIES THAT SHAPE WHO I AM.",action:"IN ACTION",hover:"HOVER OVER A LETTER",cards:[["♜","SPIRIT","brave in challenges","困難に直面しても、挑戦する気持ちと行動力を持ち続ける。"],["⌁","PASSION","driven by love for sport","スポーツ、プロジェクト、成長に誠実で持続的な情熱を持つ。"],["☼","OPTIMISM","positive through complexity","困難の中でも前向きさを保ち、行動が変化を生むと信じる。"],["▥","RESEARCH","insight through data","研究とデータを通じて課題を見つけ、根拠ある洞察を導く。"],["◎","TRANSCULTURAL","connecting across cultures","言語や文化の境界を越え、人と組織をつなぐ。"]]},
  en:{portfolio:"PORTFOLIO",section:"SKILLS",identity:"WHO I AM",number:"03",title:"MY KEYWORDS",subtitle:"FIVE QUALITIES THAT SHAPE WHO I AM.",action:"IN ACTION",hover:"HOVER OVER A LETTER",cards:[["♜","SPIRIT","brave in challenges","I embrace challenges with resilience and integrity, turning pressure into personal growth."],["⌁","PASSION","driven by love for sport","Driven by a genuine and lasting passion for sport, projects, and growth."],["☼","OPTIMISM","positive through complexity","Remaining positive through challenges and believing in the power of action."],["▥","RESEARCH","insight through data","Using research and data to identify problems and generate insight."],["◎","TRANSCULTURAL","connecting across cultures","Connecting people and organizations across languages and cultures."]]}
};
