const text={
zh:{nav1:"简介",nav2:"研究",nav3:"经历",nav4:"项目",status:"法政大学 修士二年级 · 东京",names:"朱妍 · 朱妍（シュケン）",intro:"从体育现场出发，用研究理解参与者，并把洞察转化为更好的体育体验。",contact:"联系我",aboutTitle:"在学术与体育现场之间",lead:"我关注人们如何感知、参与并评价体育体验。",about:"目前就读于法政大学修士二年级，研究外国滑雪游客的风险感知与消费者满意度。拥有北京冬奥会注册业务与大型活动协调经验，并在日本参与包容性体育活动的现场运营。计划于 2027 年进入博士阶段。",f1:"体育旅游",f2:"消费者行为",f3:"风险感知",f4:"赛事运营",researchTitle:"从雪道上的决策，理解体育消费者",researchMeta:"法政大学 · 修士研究",researchName:"外国滑雪游客的风险感知与消费者满意度",researchBody:"聚焦外国游客在滑雪旅游情境中对安全、环境与服务风险的认知，探索风险感知如何影响整体体验评价及满意度，为滑雪目的地管理与国际游客服务提供启示。",next:"计划进入博士阶段，继续开展体育消费者行为与体育旅游研究。",experienceTitle:"体育现场与组织运营",yuruOrg:"世界ゆるスポーツ協会",yuruRole:"活动企划与现场运营支持 · 日本",yuru:"参与包容性体育活动的企划与运营支持，包括现场搭建、流程辅助及参与者接待；学习如何让不同年龄、性别、运动能力与身体条件的人共同享受体育。",winterOrg:"北京冬奥组委注册中心",winterRole:"注册经理助理 · 志愿者",w1:"负责 14 家全球合作伙伴工作人员的场馆配额、岗位代码与出入权限调整，保障赛时顺利入场。",w2:"参与冬奥会、冬残奥会中英文注册说明书编制，协助 4,000 余名国内外工作人员录入岗位信息。",w3:"赛时处理 3,000 余封邮件，参与约 60 次国际奥委会及合作伙伴会议，与多个业务领域协同沟通。",award:"★ 赛会期间优秀志愿者",leadership:"组织与领导力",debateRole:"校辩论社 · 社长",debate:"统筹招新传播，任期内吸引超过 150 名新成员；策划学校首届辩论表演赛，实现活动从 0 到 1，上座率超过 80%。",unionRole:"院学生会 · 主席",union:"管理 6 个部门，统筹 5 场以上校级大型活动，累计参与人数过万；连续三年支持企业宣讲会，并负责团队管理与换届选举。",projectsTitle:"正在形成的体育提案",p1:"ゆるスポーツ提案",p2:"SUPER FORMULA 提案",soon:"内容整理中",p1body:"围绕包容性体育体验与现场参与设计的提案，之后补充背景、个人职责、过程与成果。",p2body:"面向日本顶级方程式赛事的体育商业提案，之后补充问题定义、洞察、策略与视觉资料。",footer:"研究赛场，也走进赛场。"},
ja:{nav1:"プロフィール",nav2:"研究",nav3:"経験",nav4:"プロジェクト",status:"法政大学 修士2年 · 東京",names:"朱妍（シュケン）· Zhu Yan",intro:"スポーツの現場から出発し、研究を通じて参加者を理解し、その知見をより良いスポーツ体験へ。",contact:"お問い合わせ",aboutTitle:"研究とスポーツ現場のあいだで",lead:"人々がスポーツをどのように捉え、参加し、評価するのかを探究しています。",about:"法政大学大学院修士課程2年。外国人スキー観光客のリスク認知と消費者満足を研究しています。北京2022のアクレディテーション業務とイベント調整経験を持ち、現在は日本でインクルーシブなスポーツイベント運営に携わっています。2027年から博士課程への進学を予定しています。",f1:"スポーツツーリズム",f2:"消費者行動",f3:"リスク認知",f4:"イベント運営",researchTitle:"雪上の意思決定から、スポーツ消費者を理解する",researchMeta:"法政大学 · 修士研究",researchName:"外国人スキー観光客のリスク認知と消費者満足",researchBody:"スキー観光における外国人旅行者の安全・環境・サービスに関するリスク認知と、それが体験評価と満足度に与える影響を研究しています。",next:"博士課程へ進学し、スポーツ消費者行動とスポーツツーリズムの研究を継続する予定です。",experienceTitle:"スポーツ現場と組織運営",yuruOrg:"世界ゆるスポーツ協会",yuruRole:"イベント企画・現場運営サポート · 日本",yuru:"会場設営、進行補助、参加者対応など、インクルーシブなスポーツイベントの企画・運営をサポートしています。",winterOrg:"北京冬季オリンピック組織委員会 登録センター",winterRole:"登録マネージャーアシスタント · ボランティア",w1:"グローバルパートナー14社の会場割当、役割コード、アクセス権限を管理し、円滑な入場を支援。",w2:"中英文登録マニュアル作成に参加し、国内外4,000名以上のスタッフ情報登録を支援。",w3:"大会期間中に3,000通以上のメールに対応し、IOCおよびパートナーとの会議約60回に参加。",award:"★ 大会優秀ボランティア",leadership:"組織運営・リーダーシップ",debateRole:"大学ディベート部 · 部長",debate:"新入部員150名以上を獲得。学内初のディベート模擬大会をゼロから企画し、会場稼働率80%以上を達成。",unionRole:"学部学生会 · 会長",union:"6部門を統括し、5件以上の全学大型イベントを運営。延べ参加者数は1万人を超えました。",projectsTitle:"進行中のスポーツ提案",p1:"ゆるスポーツ提案",p2:"SUPER FORMULA 提案",soon:"COMING SOON",p1body:"インクルーシブなスポーツ体験と現場参加設計に関する提案。詳細は今後追加します。",p2body:"日本最高峰のフォーミュラレースを対象としたスポーツビジネス提案。詳細は今後追加します。",footer:"スポーツを研究し、現場にも立つ。"},
en:{nav1:"Profile",nav2:"Research",nav3:"Experience",nav4:"Projects",status:"M.A. Year 2 at Hosei University · Tokyo",names:"Zhu Yan · 朱妍（シュケン）",intro:"Starting from the field, I use research to understand participants and turn insight into better sport experiences.",contact:"Get in touch",aboutTitle:"Between research and the field",lead:"I study how people perceive, participate in, and evaluate sport experiences.",about:"I am a second-year master’s student at Hosei University researching risk perception and consumer satisfaction among international ski tourists. My experience spans accreditation operations at Beijing 2022, large-scale event coordination, and inclusive sport event operations in Japan. I plan to begin doctoral study in 2027.",f1:"Sport tourism",f2:"Consumer behavior",f3:"Risk perception",f4:"Event operations",researchTitle:"Understanding sport consumers through decisions on the slopes",researchMeta:"Hosei University · Master’s Research",researchName:"Risk Perception and Consumer Satisfaction among International Ski Tourists",researchBody:"The study examines perceptions of safety, environmental, and service risks in ski tourism and how they influence experience evaluations and satisfaction.",next:"Planning to pursue doctoral study in sport consumer behavior and sport tourism from 2027.",experienceTitle:"Sport field & organizational operations",yuruOrg:"World Yuru Sports Association",yuruRole:"Event Planning & On-site Operations Support · Japan",yuru:"Supporting inclusive sport events through venue setup, program assistance, and participant support.",winterOrg:"Beijing 2022 Organising Committee · Accreditation Centre",winterRole:"Assistant Accreditation Manager · Volunteer",w1:"Managed venue quotas, role codes, and access permissions for staff from 14 Worldwide Olympic Partners.",w2:"Contributed to Chinese and English accreditation manuals and supported data entry for 4,000+ staff.",w3:"Handled 3,000+ emails and joined approximately 60 IOC and partner meetings during the Games.",award:"★ Outstanding Games Volunteer",leadership:"Organization & leadership",debateRole:"University Debate Club · President",debate:"Led recruitment of 150+ members and created the university’s first debate showcase, reaching 80%+ attendance.",unionRole:"Faculty Student Union · President",union:"Oversaw six departments and coordinated 5+ major events with more than 10,000 total participants.",projectsTitle:"Sport proposals in progress",p1:"Yuru Sports Proposal",p2:"SUPER FORMULA Proposal",soon:"COMING SOON",p1body:"A proposal exploring inclusive sport experiences and field participation design. Details will be added.",p2body:"A sport business proposal for Japan’s premier formula racing series. Details will be added.",footer:"Researching sport. Working in the field."}
};
const buttons=document.querySelectorAll("[data-lang]"),nodes=document.querySelectorAll("[data-k]");
function setLang(lang){nodes.forEach(n=>{const v=text[lang][n.dataset.k];if(v)n.textContent=v});buttons.forEach(b=>{const on=b.dataset.lang===lang;b.classList.toggle("active",on);b.setAttribute("aria-pressed",on)});document.documentElement.lang=lang==="zh"?"zh-CN":lang;localStorage.setItem("lang",lang)}
buttons.forEach(b=>b.onclick=()=>setLang(b.dataset.lang));setLang(localStorage.getItem("lang")||"zh");
const displayNames={zh:"朱妍",ja:"朱妍（シュケン）",en:"Zhu Yan"};
function setDisplayName(lang){document.querySelector('[data-k="names"]').textContent=displayNames[lang]}
buttons.forEach(b=>b.onclick=()=>{setLang(b.dataset.lang);setDisplayName(b.dataset.lang)});
setDisplayName(localStorage.getItem("lang")||"zh");
